[tool.poetry]
name = "english-to-iql-demo"
version = "0.1.0"
description = ""
authors = ["joao loula <jloula@mit.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.4.2"
openai = "^0.28.1"
ipdb = "^0.13.13"
fastapi = "^0.103.2"
uvicorn = "^0.23.2"
polars = "^0.19.8"
jinja2 = "^3.1.2"
jinja2-fragments = "^1.1.0"
python-multipart = "^0.0.6"
pytailwindcss = "^0.2.0"
black = "^23.9.1"
requests = "^2.31.0"
transformers = "^4.38.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
