[tool.poetry]
name = "english-to-iql-demo"
version = "0.1.0"
description = ""
authors = ["joao loula <jloula@mit.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^7.4.2"
openai = "^0.28.1"
ipdb = "^0.13.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
